// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDStIwvF4q2bKMvkDCNruKfhsBWgaJG_LQ',
    appId: '1:358710272872:android:cd1d190335a59a46eaacdd',
    messagingSenderId: '358710272872',
    projectId: 'firecarse',
    storageBucket: 'firecarse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiKxMcGpfkybmeFSLow0RFEnIDkj_XtOA',
    appId: '1:358710272872:ios:3cbbd4b673558bf7eaacdd',
    messagingSenderId: '358710272872',
    projectId: 'firecarse',
    storageBucket: 'firecarse.appspot.com',
    androidClientId: '358710272872-snd89tmcjd65v66a6isbs4ppsqr5l7nj.apps.googleusercontent.com',
    iosClientId: '358710272872-ste673tjo6cgtm6sn6kr8r0scdp52j51.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireCarse',
  );
}
